import './styles.css';
import { Camera, CameraResultType, CameraSource } from '@capacitor/camera';
import { LocalNotifications } from '@capacitor/local-notifications';
import { Share } from '@capacitor/share';

const APP_VERSION='1.1.1';
const STORAGE_KEY='operastep-v1.1.1-state';
const app=document.querySelector('#app');
const eur=v=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(Number(v||0));
const today=()=>new Date().toISOString().slice(0,10);
const uid=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const daysTo=d=>{if(!d)return 9999;return Math.ceil((new Date(`${d}T00:00:00`)-new Date(`${today()}T00:00:00`))/86400000)};
const emptyState=()=>({version:1,onboarded:false,project:null,quotes:[],costs:[],tasks:[],payments:[]});
let state;try{state=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null')||emptyState()}catch{state=emptyState()}
let receipt=null;

function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function matured(q){return(q.lines||[]).reduce((s,l)=>s+Number(l.value||0)*Number(l.pct||0)/100,0)}
function safe(q){return Math.max(0,matured(q)*(1-Number(q.retention||0)/100)-Number(q.paid||0))}
function totalSafe(){return state.quotes.reduce((s,q)=>s+safe(q),0)}
function totalQuotes(){return state.quotes.reduce((s,q)=>s+Number(q.total||0),0)}
function totalPaid(){return state.quotes.reduce((s,q)=>s+Number(q.paid||0),0)}
function externalCosts(){return state.costs.filter(c=>!c.included).reduce((s,c)=>s+Number(c.planned||0),0)}
function forecast(){return totalQuotes()+externalCosts()}
function taskPct(){return state.tasks.length?Math.round(state.tasks.filter(t=>t.done).length/state.tasks.length*100):0}
function leadDays(c){const t=`${c.name} ${c.category}`.toLowerCase();if(/cucina/.test(t))return 60;if(/infiss|porta/.test(t))return 45;if(/matton|piastrell|paviment|rivest/.test(t))return 21;if(/sanitar|rubinet/.test(t))return 21;if(/illumin/.test(t))return 14;return 10}

function tips(){
 const a=[];
 if(!state.quotes.length)a.push(['blue','Aggiungi il primo preventivo','Dividilo per lavorazioni: OperaStep userà quelle voci per controllare avanzamento e pagamenti.']);
 if(!state.tasks.length)a.push(['blue','Crea il piano lavori','Puoi partire da zero oppure generare un piano base e personalizzarlo.']);
 for(const q of state.quotes){const ex=Number(q.paid||0)-matured(q);if(ex>0)a.push(['red',`Pagamento troppo avanti · ${q.supplier}`,`Hai pagato ${eur(ex)} più del valore maturato.`]);if(q.lastUpdate&&Math.abs(daysTo(q.lastUpdate))>7)a.push(['amber',`Aggiorna ${q.supplier}`,'Sono passati più di 7 giorni dall’ultimo controllo.']);}
 for(const c of state.costs){if(['ricevuto','pagato'].includes(c.status)||!c.neededBy)continue;const d=daysTo(c.neededBy),lead=leadDays(c);if(d<0)a.push(['red',`${c.name} è in ritardo`,`Serviva entro ${c.neededBy}.`]);else if(d<=lead&&c.status!=='ordinato')a.push([d<=7?'red':'amber',`È il momento di ordinare: ${c.name}`,`Mancano ${d} giorni; per questa voce conviene considerare circa ${lead} giorni di anticipo.`]);}
 const overdue=state.tasks.filter(t=>!t.done&&t.due&&daysTo(t.due)<0);if(overdue.length)a.push(['red',`${overdue.length} attività in ritardo`,overdue[0].title]);
 const b=Number(state.project?.budget||0);if(b&&forecast()>b)a.push(['red','Budget previsto superato',`La previsione è ${eur(forecast()-b)} sopra il budget.`]);
 if(!a.length)a.push(['green','Piano sotto controllo','Non vedo criticità urgenti. Continua ad aggiornare lavori, acquisti e scadenze.']);
 return a.slice(0,6);
}

function shell(body,active='home'){return `<div class="shell">${body}<nav><button data-nav="home" class="${active==='home'?'active':''}">⌂<small>Home</small></button><button data-nav="quotes" class="${active==='quotes'?'active':''}">▤<small>Preventivi</small></button><button data-nav="plan" class="${active==='plan'?'active':''}">✓<small>Piano</small></button><button data-nav="costs" class="${active==='costs'?'active':''}">◫<small>Costi</small></button><button data-nav="payments" class="${active==='payments'?'active':''}">€<small>Pagamenti</small></button></nav></div>`}
function hero(title,sub,back=false){return `<header>${back?'<button class="back" data-nav="home">←</button>':'<div class="brand">Opera<span>Step</span></div>'}<div class="eyebrow">${esc(state.project?.name||'OperaStep')}</div><h1>${title}</h1><p>${sub}</p></header>`}
function bindNav(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>route(b.dataset.nav))}
function empty(title,text){return `<div class="empty"><b>${title}</b><p>${text}</p></div>`}

function onboarding(){app.innerHTML=`<main class="onboarding"><div class="brand big">Opera<span>Step</span></div><div class="intro"><div class="kicker">RISTRUTTURARE CON PIÙ CONTROLLO</div><h1>Ogni fase.<br>Il giusto pagamento.</h1><p>Pianifica lavori, acquisti e scadenze. Controlla preventivi, budget e pagamenti in un unico posto.</p></div><div class="features"><div><b>01</b><span>Preventivi e avanzamento reale</span></div><div><b>02</b><span>Checklist e promemoria</span></div><div><b>03</b><span>Tips smart su ritardi e costi</span></div></div><button class="primary" id="start">Crea il mio progetto</button><small class="privacy">Nessun dato demo. Nessun account obbligatorio. · v${APP_VERSION}</small></main>`;document.querySelector('#start').onclick=projectSetup}

function projectSetup(){app.innerHTML=`<main class="setup"><div class="brand dark">Opera<span>Step</span></div><div class="versionMark">VERSIONE ${APP_VERSION} · BUDGET SMART</div><h1>Crea il tuo progetto.</h1><p>Inserisci i dati di base. Subito dopo potrai indicare il tuo budget oppure chiedere a OperaStep una stima orientativa.</p><label>Nome progetto<input id="name" placeholder="es. Ristrutturazione casa"></label><label>Tipo<select id="type"><option>Ristrutturazione completa</option><option>Ristrutturazione parziale</option><option>Bagno</option><option>Cucina</option><option>Altro</option></select></label><div class="two"><label>Inizio<input id="startDate" type="date"></label><label>Fine prevista<input id="endDate" type="date"></label></div><button class="primary" id="continueProject">Continua</button></main>`;document.querySelector('#continueProject').onclick=()=>{const name=document.querySelector('#name').value.trim();if(!name)return alert('Inserisci il nome del progetto');state=emptyState();state.onboarded=true;state.project={name,type:document.querySelector('#type').value,budget:0,budgetSource:'',estimate:null,startDate:document.querySelector('#startDate').value,endDate:document.querySelector('#endDate').value};budgetChoice()}}

function budgetChoice(){app.innerHTML=`<main class="setup"><div class="brand dark">Opera<span>Step</span></div><div class="kicker">BUDGET INTELLIGENTE</div><h1>Come vuoi impostare il budget?</h1><p>Puoi partire da una cifra che hai già stabilito oppure farti aiutare da OperaStep con una stima orientativa.</p><button class="choice" id="known"><b>Ho già un budget</b><span>Inserisci l'importo che hai deciso di destinare ai lavori.</span></button><button class="choice featured" id="estimate"><b>Aiutami a stimarlo</b><span>Rispondi a poche domande e ottieni un intervallo con dettaglio per categorie.</span></button><div class="notice">La stima OperaStep è orientativa e non sostituisce i preventivi dei professionisti.</div></main>`;document.querySelector('#known').onclick=knownBudget;document.querySelector('#estimate').onclick=estimateBudgetForm}

function knownBudget(){app.innerHTML=`<main class="setup"><div class="brand dark">Opera<span>Step</span></div><h1>Qual è il tuo budget?</h1><p>Potrai modificarlo in qualsiasi momento.</p><label>Budget disponibile<input id="knownAmount" type="number" inputmode="numeric" placeholder="es. 80000"></label><button class="primary" id="saveKnown">Usa questo budget</button><button class="secondary" id="backBudget">Indietro</button></main>`;document.querySelector('#backBudget').onclick=budgetChoice;document.querySelector('#saveKnown').onclick=()=>{const b=Number(document.querySelector('#knownAmount').value||0);if(b<=0)return alert('Inserisci un importo');state.project.budget=b;state.project.budgetSource='user';state.project.estimate=null;save();home()}}

function estimateBudgetForm(){app.innerHTML=`<main class="setup"><div class="brand dark">Opera<span>Step</span></div><div class="kicker">STIMA · 1 MINUTO</div><h1>Raccontaci la ristrutturazione.</h1><p>Questi dati servono solo a costruire una prima stima.</p><label>Metratura dell'immobile (m²)<input id="sqm" type="number" inputmode="numeric" placeholder="es. 120"></label><label>Intervento<select id="scope"><option value="complete">Completa</option><option value="partial">Parziale</option><option value="light">Leggera / finiture</option></select></label><label>Livello finiture<select id="finish"><option value="essential">Essenziale</option><option value="standard" selected>Standard</option><option value="premium">Premium</option></select></label><div class="two"><label>Bagni coinvolti<input id="bathrooms" type="number" min="0" value="1"></label><label>Cucina coinvolta<select id="kitchen"><option value="yes">Sì</option><option value="no">No</option></select></label></div><label>Impianti<select id="systems"><option value="full">Da rifare</option><option value="partial">Parziali</option><option value="none">Non previsti</option></select></label><button class="primary" id="calcEstimate">Calcola la stima</button><button class="secondary" id="backEstimate">Indietro</button></main>`;document.querySelector('#backEstimate').onclick=budgetChoice;document.querySelector('#calcEstimate').onclick=()=>{const sqm=Number(document.querySelector('#sqm').value||0);if(sqm<10)return alert('Inserisci una metratura valida');const data={sqm,scope:document.querySelector('#scope').value,finish:document.querySelector('#finish').value,bathrooms:Number(document.querySelector('#bathrooms').value||0),kitchen:document.querySelector('#kitchen').value==='yes',systems:document.querySelector('#systems').value};estimateResult(buildEstimate(data))}}

function buildEstimate(d){const scope={complete:1,partial:.62,light:.34}[d.scope],finish={essential:.85,standard:1,premium:1.35}[d.finish];let core=d.sqm*760*scope*finish;let systems=d.systems==='full'?d.sqm*170:d.systems==='partial'?d.sqm*85:0;let wet=(d.bathrooms*6500+(d.kitchen?7500:0))*finish;let works=core*.43,materials=core*.32+wet,professionals=core*.10,other=core*.15;let subtotal=works+systems+materials+professionals+other;let contingency=subtotal*.10;let mid=Math.round((subtotal+contingency)/500)*500;let low=Math.round(mid*.88/500)*500,high=Math.round(mid*1.14/500)*500;const categories=[['Lavori edili',works],['Impianti',systems],['Materiali e finiture',materials],['Professionisti',professionals],['Altri costi',other],['Imprevisti',contingency]].map(([name,value])=>({name,value:Math.round(value/100)*100}));return{...d,low,mid,high,categories,createdAt:today()}}

function estimateResult(e){app.innerHTML=`<main class="setup"><div class="brand dark">Opera<span>Step</span></div><div class="kicker">LA TUA STIMA</div><h1>${eur(e.low)} – ${eur(e.high)}</h1><p>Budget di riferimento: <b>${eur(e.mid)}</b>. È un valore orientativo costruito sui dati inseriti.</p><div class="card estimateBreakdown">${e.categories.map(c=>`<div><span>${esc(c.name)}</span><b>${eur(c.value)}</b></div>`).join('')}</div><div class="notice">I prezzi reali dipendono da zona, fornitori, condizioni dell'immobile e scelte finali. I preventivi reali sostituiranno progressivamente questa stima.</div><button class="primary" id="useEstimate">Usa questa stima</button><button class="secondary" id="editEstimate">Modifica le risposte</button></main>`;document.querySelector('#editEstimate').onclick=estimateBudgetForm;document.querySelector('#useEstimate').onclick=()=>{state.project.estimate=e;state.project.budget=e.mid;state.project.budgetSource='estimate';save();home()}}

function quoteEstimateCategory(q){const t=`${q.category} ${q.title}`.toLowerCase();if(/elettr|idraul|impiant/.test(t))return'Impianti';if(/paviment|rivest|cucina|bagn|sanitar|infiss|porta|illumin|material/.test(t))return'Materiali e finiture';if(/architet|geometr|ingegner|profession/.test(t))return'Professionisti';if(/mur|cartong|demol|pittur|intonac|rasatur|edil/.test(t))return'Lavori edili';return'Altri costi'}
function estimateComparison(){const e=state.project?.estimate;if(!e)return null;const confirmed=totalQuotes()+externalCosts(),saving=e.mid-confirmed,pct=e.mid?saving/e.mid*100:0;const by=e.categories.map(c=>{const real=state.quotes.filter(q=>quoteEstimateCategory(q)===c.name).reduce((s,q)=>s+Number(q.total||0),0)+(c.name==='Altri costi'?externalCosts():0);return{name:c.name,estimate:c.value,real,diff:c.value-real}});return{confirmed,saving,pct,by}}


function home(){const b=Number(state.project.budget||0),remaining=b-forecast(),cmp=estimateComparison();const comparison=cmp?`<div class="sectionTitle">Stima vs preventivi</div><div class="card comparison"><div class="compareTop"><div><small>Stima iniziale</small><b>${eur(state.project.estimate.mid)}</b></div><div><small>Preventivi + costi</small><b>${eur(cmp.confirmed)}</b></div></div>${cmp.confirmed>0?`<div class="saving ${cmp.saving>=0?'positive':'negative'}"><small>${cmp.saving>=0?'RISPARMIO RISPETTO ALLA STIMA':'SOPRA LA STIMA'}</small><strong>${cmp.saving>=0?'- ':'+ '}${eur(Math.abs(cmp.saving))}</strong><span>${Math.abs(cmp.pct).toFixed(1)}%</span></div><div class="categoryCompare">${cmp.by.filter(x=>x.real>0).map(x=>`<div><span>${esc(x.name)}</span><small>Stima ${eur(x.estimate)} · Reale ${eur(x.real)}</small><b class="${x.diff>=0?'good':'bad'}">${x.diff>=0?'-':'+'}${eur(Math.abs(x.diff))}</b></div>`).join('')}</div>`:'<p class="muted">Aggiungi i preventivi: OperaStep evidenzierà automaticamente quanto stai risparmiando rispetto alla stima iniziale.</p>'}</div>`:'';app.innerHTML=shell(`${hero('La ristrutturazione, sotto controllo.','Budget, lavori, acquisti e pagamenti in un unico percorso.')}<section><div class="card heroCard"><div class="label">PUOI PAGARE OGGI</div><div class="amount">${eur(totalSafe())}</div><p>${state.quotes.length?'Calcolato sul valore realmente maturato.':'Aggiungi il primo preventivo per attivare il controllo.'}</p><div class="metrics"><div><small>Preventivi</small><b>${eur(totalQuotes())}</b></div><div><small>Pagato</small><b>${eur(totalPaid())}</b></div><div><small>Altri costi</small><b>${eur(externalCosts())}</b></div><div><small>Piano</small><b>${taskPct()}%</b></div></div></div>${comparison}<div class="sectionTitle">Assistente OperaStep <em>SMART</em></div><div class="card">${tips().map(t=>`<div class="tip ${t[0]}"><i></i><div><b>${esc(t[1])}</b><p>${esc(t[2])}</p></div></div>`).join('')}</div><div class="sectionTitle">Budget & previsione</div><div class="card budget"><div><span>${state.project.budgetSource==='estimate'?'Budget stimato':'Budget'}</span><b>${eur(b)}</b></div><div><span>Previsione</span><b>${eur(forecast())}</b></div><div class="bar"><i style="width:${b?Math.min(100,forecast()/b*100):0}%"></i></div><small>${b?remaining>=0?`Margine previsto ${eur(remaining)}`:`Superamento previsto ${eur(Math.abs(remaining))}`:'Imposta un budget per controllare lo scostamento.'}</small></div></section>`,'home');bindNav();const eb=document.querySelector('#editBudget');if(eb)eb.onclick=budgetChoice}

function quotes(){app.innerHTML=shell(`${hero('Preventivi','Inserisci imprese, fornitori e singole lavorazioni.',true)}<section><button class="primary" id="newQuote">+ Inserisci preventivo</button><div class="sectionTitle">Preventivi</div>${state.quotes.length?state.quotes.map(q=>`<div class="card quote" data-q="${q.id}"><div><span class="badge">${esc(q.category)}</span><h3>${esc(q.supplier)}</h3><p>${esc(q.title)}</p></div><b>${eur(q.total)}</b><div class="bar full"><i style="width:${Math.min(100,matured(q)/Math.max(1,q.total)*100)}%"></i></div><small>Maturato ${eur(matured(q))} · Pagato ${eur(q.paid)} · Pagabile ${eur(safe(q))}</small></div>`).join(''):empty('Nessun preventivo','Aggiungi il primo preventivo per iniziare.')}</section>`,'quotes');bindNav();document.querySelector('#newQuote').onclick=quoteForm;document.querySelectorAll('[data-q]').forEach(x=>x.onclick=()=>quoteDetail(x.dataset.q))}

function quoteForm(){app.innerHTML=shell(`${hero('Nuovo preventivo','Nessun dato precompilato: inserisci solo ciò che appartiene al tuo progetto.',true)}<section><div class="card form"><label>Fornitore<input id="supplier" placeholder="Impresa / professionista"></label><label>Categoria<select id="cat"><option>Muratura</option><option>Cartongesso</option><option>Impianto elettrico</option><option>Impianto idraulico</option><option>Pavimenti e rivestimenti</option><option>Infissi</option><option>Pittura</option><option>Cucina</option><option>Bagni</option><option>Altro</option></select></label><label>Titolo<input id="title" placeholder="es. Opere murarie"></label><div class="two"><label>Totale<input id="total" type="number" placeholder="0"></label><label>Ritenuta %<input id="ret" type="number" value="10"></label></div><label>Voci del preventivo<textarea id="lines" rows="6" placeholder="Una riga per voce. Esempio:\nDemolizioni = 2500\nTracce = 1200\nIntonaco = 1800"></textarea></label><label>Note<textarea id="note" rows="3"></textarea></label><button class="primary" id="saveQuote">Salva preventivo</button></div></section>`,'quotes');bindNav();document.querySelector('#saveQuote').onclick=()=>{const supplier=document.querySelector('#supplier').value.trim(),title=document.querySelector('#title').value.trim(),total=Number(document.querySelector('#total').value||0);if(!supplier||!title||total<=0)return alert('Completa fornitore, titolo e totale');const parsed=document.querySelector('#lines').value.split('\n').map(x=>x.trim()).filter(Boolean).map(row=>{const m=row.match(/^(.*?)\s*[=:;-]\s*([0-9.,]+)\s*€?$/);return m?{id:uid('l'),name:m[1].trim(),value:Number(m[2].replace('.','').replace(',','.')),pct:0,done:false}:null}).filter(Boolean);state.quotes.push({id:uid('q'),supplier,title,category:document.querySelector('#cat').value,total,retention:Number(document.querySelector('#ret').value||0),paid:0,lastUpdate:today(),note:document.querySelector('#note').value,lines:parsed.length?parsed:[{id:uid('l'),name:'Lavorazione generale',value:total,pct:0,done:false}]});save();quotes()}}

function quoteDetail(id){const q=state.quotes.find(x=>x.id===id);if(!q)return quotes();app.innerHTML=shell(`${hero(q.supplier,`${q.category} · ${q.title}`,true)}<section><div class="card summary"><div><small>Preventivo</small><b>${eur(q.total)}</b></div><div><small>Maturato</small><b>${eur(matured(q))}</b></div><div><small>Pagato</small><b>${eur(q.paid)}</b></div><div><small>Pagabile ora</small><b>${eur(safe(q))}</b></div></div><div class="sectionTitle">Avanzamento</div><div class="card">${q.lines.map((l,i)=>`<div class="work"><div><label class="check"><input type="checkbox" data-done="${i}" ${l.done?'checked':''}><span></span><b>${esc(l.name)}</b></label><small>${eur(l.value)}</small></div><div class="range"><span>${l.pct}%</span><input type="range" min="0" max="100" step="5" value="${l.pct}" data-range="${i}"></div></div>`).join('')}<button class="primary" id="saveProgress">Salva avanzamento</button></div><button class="secondary" id="payThis">Registra pagamento</button></section>`,'quotes');bindNav();document.querySelectorAll('[data-range]').forEach(r=>r.oninput=e=>{const l=q.lines[Number(e.target.dataset.range)];l.pct=Number(e.target.value);l.done=l.pct===100;quoteDetail(id)});document.querySelectorAll('[data-done]').forEach(c=>c.onchange=e=>{const l=q.lines[Number(e.target.dataset.done)];l.done=e.target.checked;l.pct=l.done?100:Math.min(l.pct,95);quoteDetail(id)});document.querySelector('#saveProgress').onclick=()=>{q.lastUpdate=today();save();home()};document.querySelector('#payThis').onclick=()=>paymentForm(id)}

function suggestedTasks(){const names=[['Preparazione','Confrontare e confermare i preventivi principali'],['Preparazione','Confermare misure e progetto esecutivo'],['Demolizioni','Completare demolizioni e smaltimento'],['Muratura','Completare opere murarie e tracce'],['Impianti','Verificare impianti prima delle chiusure'],['Materiali','Confermare ordini di pavimenti e rivestimenti'],['Pavimenti e rivestimenti','Posare pavimenti e rivestimenti'],['Finiture','Rasare e pitturare'],['Montaggi','Montare sanitari, porte e illuminazione'],['Collaudi','Controllo finale prima del saldo']];const start=state.project.startDate?new Date(state.project.startDate):new Date(),end=state.project.endDate?new Date(state.project.endDate):new Date(start.getTime()+120*86400000),span=Math.max(30,Math.round((end-start)/86400000));return names.map((x,i)=>{const d=new Date(start.getTime()+Math.round(span*(i+1)/(names.length+1))*86400000);return{id:uid('t'),phase:x[0],title:x[1],due:d.toISOString().slice(0,10),done:false,note:'Piano base suggerito'}})}
function plan(){app.innerHTML=shell(`${hero('Piano lavori','Checklist e scadenze del cantiere.',true)}<section><div class="two"><button class="primary" id="newTask">+ Attività</button>${state.tasks.length?'':'<button class="secondary" id="suggest">Genera piano base</button>'}</div><div class="sectionTitle">Checklist · ${taskPct()}%</div>${state.tasks.length?state.tasks.map(t=>`<div class="task ${t.done?'done':''}"><label><input type="checkbox" data-task="${t.id}" ${t.done?'checked':''}><span></span><div><b>${esc(t.title)}</b><small>${esc(t.phase)}${t.due?` · ${t.due}`:''}</small></div></label>${!t.done&&t.due&&daysTo(t.due)<0?'<em>In ritardo</em>':''}</div>`).join(''):empty('Piano ancora vuoto','Aggiungi attività oppure genera una traccia iniziale.')}</section>`,'plan');bindNav();document.querySelector('#newTask').onclick=taskForm;document.querySelector('#suggest')?.addEventListener('click',()=>{if(confirm('Generare un piano base modificabile?')){state.tasks=suggestedTasks();save();plan()}});document.querySelectorAll('[data-task]').forEach(c=>c.onchange=e=>{const t=state.tasks.find(x=>x.id===e.target.dataset.task);t.done=e.target.checked;save();plan()})}
function taskForm(){app.innerHTML=shell(`${hero('Nuova attività','Aggiungi un passo del cantiere e una scadenza.',true)}<section><div class="card form"><label>Attività<input id="tTitle"></label><label>Fase<select id="tPhase"><option>Preparazione</option><option>Demolizioni</option><option>Muratura</option><option>Impianti</option><option>Materiali</option><option>Pavimenti e rivestimenti</option><option>Finiture</option><option>Montaggi</option><option>Collaudi</option><option>Altro</option></select></label><label>Scadenza<input id="tDue" type="date"></label><label>Nota<textarea id="tNote" rows="3"></textarea></label><label class="toggle"><input id="rem" type="checkbox" checked> Promemoria sul telefono</label><button class="primary" id="saveTask">Salva attività</button></div></section>`,'plan');bindNav();document.querySelector('#saveTask').onclick=async()=>{const title=document.querySelector('#tTitle').value.trim(),due=document.querySelector('#tDue').value,id=uid('t');if(!title)return alert('Inserisci attività');state.tasks.push({id,phase:document.querySelector('#tPhase').value,title,due,done:false,note:document.querySelector('#tNote').value});save();if(document.querySelector('#rem').checked&&due)await schedule(title,due,id);plan()}}
async function schedule(title,date,id){try{const p=await LocalNotifications.requestPermissions();const at=new Date(`${date}T09:00:00`);if(p.display==='granted'&&at>Date.now())await LocalNotifications.schedule({notifications:[{id:Math.abs([...id].reduce((a,c)=>((a<<5)-a)+c.charCodeAt(0),0))%2147483000,title:'OperaStep · Promemoria',body:title,schedule:{at}}]})}catch{}}

function costs(){app.innerHTML=shell(`${hero('Costi & acquisti','Materiali, manodopera e spese extra-preventivo.',true)}<section><button class="primary" id="newCost">+ Aggiungi costo / acquisto</button><div class="sectionTitle">Costi</div>${state.costs.length?state.costs.map(c=>`<div class="card cost"><div><span class="badge">${esc(c.type)}</span><h3>${esc(c.name)}</h3><p>${esc(c.category)}${c.neededBy?` · serve ${c.neededBy}`:''}</p></div><b>${eur(c.planned)}</b><select data-status="${c.id}"><option value="da_confermare" ${c.status==='da_confermare'?'selected':''}>Da confermare</option><option value="da_acquistare" ${c.status==='da_acquistare'?'selected':''}>Da acquistare</option><option value="ordinato" ${c.status==='ordinato'?'selected':''}>Ordinato</option><option value="ricevuto" ${c.status==='ricevuto'?'selected':''}>Ricevuto</option><option value="pagato" ${c.status==='pagato'?'selected':''}>Pagato</option></select></div>`).join(''):empty('Nessun costo','Aggiungi materiali, servizi e manodopera con la data in cui servono.')}</section>`,'costs');bindNav();document.querySelector('#newCost').onclick=costForm;document.querySelectorAll('[data-status]').forEach(s=>s.onchange=e=>{state.costs.find(c=>c.id===e.target.dataset.status).status=e.target.value;save();costs()})}
function costForm(){app.innerHTML=shell(`${hero('Nuovo costo','Aggiungi ciò che serve al progetto e quando deve essere disponibile.',true)}<section><div class="card form"><label>Voce<input id="cName" placeholder="es. Mattonelle, Muratore, Sanitari"></label><div class="two"><label>Tipo<select id="cType"><option>Materiale</option><option>Manodopera</option><option>Professionista</option><option>Trasporto</option><option>Noleggio</option><option>Altro</option></select></label><label>Categoria<select id="cCat"><option>Muratura</option><option>Impianti</option><option>Pavimenti e rivestimenti</option><option>Bagni</option><option>Cucina</option><option>Infissi</option><option>Pittura</option><option>Illuminazione</option><option>Arredi</option><option>Altro</option></select></label></div><div class="two"><label>Costo previsto<input id="cPlanned" type="number"></label><label>Costo effettivo<input id="cActual" type="number"></label></div><label>Fornitore<input id="cSupplier"></label><label>Quando serve?<input id="cNeeded" type="date"></label><label>Stato<select id="cStatus"><option value="da_confermare">Da confermare</option><option value="da_acquistare">Da acquistare</option><option value="ordinato">Ordinato</option><option value="ricevuto">Ricevuto</option><option value="pagato">Pagato</option></select></label><label class="toggle"><input id="cIncluded" type="checkbox"> Già compreso in un preventivo</label><label class="toggle"><input id="cRem" type="checkbox" checked> Promemoria sul telefono</label><label>Note<textarea id="cNote" rows="3"></textarea></label><button class="primary" id="saveCost">Salva costo</button></div></section>`,'costs');bindNav();document.querySelector('#saveCost').onclick=async()=>{const name=document.querySelector('#cName').value.trim(),due=document.querySelector('#cNeeded').value,id=uid('c');if(!name)return alert('Inserisci voce');state.costs.push({id,name,type:document.querySelector('#cType').value,category:document.querySelector('#cCat').value,planned:Number(document.querySelector('#cPlanned').value||0),actual:Number(document.querySelector('#cActual').value||0),supplier:document.querySelector('#cSupplier').value,neededBy:due,status:document.querySelector('#cStatus').value,included:document.querySelector('#cIncluded').checked,note:document.querySelector('#cNote').value});save();if(document.querySelector('#cRem').checked&&due)await schedule(`Ricorda: ${name}`,due,id);costs()}}

function payments(){app.innerHTML=shell(`${hero('Pagamenti','Registra ogni pagamento collegandolo al preventivo corretto.',true)}<section>${state.quotes.length?'<button class="primary" id="newPay">+ Nuovo pagamento</button>':'<div class="notice">Inserisci prima un preventivo.</div>'}<div class="sectionTitle">Storico</div><div class="card">${state.payments.length?state.payments.slice().reverse().map(p=>{const q=state.quotes.find(x=>x.id===p.quoteId);return `<div class="payment"><div><b>${eur(p.amount)} · ${esc(q?.supplier||'Fornitore')}</b><small>${p.date} · ${esc(p.method)} · ${esc(p.note||'')}</small></div>${p.receipt?'<span>📎</span>':''}</div>`}).join(''):'<p class="muted">Nessun pagamento registrato.</p>'}</div></section>`,'payments');bindNav();document.querySelector('#newPay')?.addEventListener('click',()=>paymentForm())}
function paymentForm(pre=''){receipt=null;app.innerHTML=shell(`${hero('Nuovo pagamento','OperaStep verifica il limite consigliato sul lavoro maturato.',true)}<section><div class="card form"><label>Preventivo<select id="pQuote">${state.quotes.map(q=>`<option value="${q.id}" ${q.id===pre?'selected':''}>${esc(q.supplier)} · ${esc(q.category)}</option>`).join('')}</select></label><div id="limit"></div><label>Importo<input id="pAmount" type="number"></label><div class="two"><label>Data<input id="pDate" type="date" value="${today()}"></label><label>Metodo<select id="pMethod"><option>Bonifico</option><option>Contanti</option><option>Carta</option><option>Assegno</option></select></label></div><label>Nota<input id="pNote"></label><div class="two"><button class="secondary" id="camera">Foto bonifico</button><button class="secondary" id="gallery">Galleria</button></div><div id="validation"></div><button class="primary" id="savePay">Registra pagamento</button></div></section>`,'payments');bindNav();const val=()=>{const q=state.quotes.find(x=>x.id===document.querySelector('#pQuote').value),amt=Number(document.querySelector('#pAmount').value||0),lim=safe(q);document.querySelector('#limit').innerHTML=`<div class="safe"><small>Massimo consigliato</small><b>${eur(lim)}</b></div>`;document.querySelector('#validation').innerHTML=amt>lim?`<div class="danger">Supera il limite di ${eur(amt-lim)}</div>`:amt>0?'<div class="ok">Pagamento coerente</div>':'';document.querySelector('#savePay').disabled=amt<=0||amt>lim};document.querySelector('#pAmount').oninput=val;document.querySelector('#pQuote').onchange=val;val();document.querySelector('#camera').onclick=()=>capture(CameraSource.Camera);document.querySelector('#gallery').onclick=()=>capture(CameraSource.Photos);document.querySelector('#savePay').onclick=()=>{const q=state.quotes.find(x=>x.id===document.querySelector('#pQuote').value),amt=Number(document.querySelector('#pAmount').value||0);if(amt<=0||amt>safe(q))return;state.payments.push({id:uid('p'),quoteId:q.id,amount:amt,date:document.querySelector('#pDate').value,method:document.querySelector('#pMethod').value,note:document.querySelector('#pNote').value,receipt});q.paid=Number(q.paid||0)+amt;save();payments()}}
async function capture(source){try{const p=await Camera.getPhoto({quality:60,resultType:CameraResultType.DataUrl,source});receipt=p.dataUrl;alert('Ricevuta allegata')}catch{}}

function project(){app.innerHTML=shell(`${hero('Progetto','Impostazioni, privacy e condivisione.',true)}<section><div class="card form"><label>Nome<input id="prName" value="${esc(state.project.name)}"></label><label>Tipo<input id="prType" value="${esc(state.project.type)}"></label><label>Budget<input id="prBudget" type="number" value="${state.project.budget||0}"></label><div class="two"><label>Inizio<input id="prStart" type="date" value="${state.project.startDate||''}"></label><label>Fine<input id="prEnd" type="date" value="${state.project.endDate||''}"></label></div><button class="primary" id="saveProject">Salva progetto</button></div><div class="sectionTitle">Condividi</div><div class="card"><button class="secondary" id="share">Condividi riepilogo progetto</button><p class="muted">Condivide solo un riepilogo testuale scelto da te.</p></div><div class="sectionTitle">Privacy e dati</div><div class="card"><b>Privacy by default</b><p class="muted">OperaStep 1.0 non richiede account e salva i dati localmente sul dispositivo.</p><button class="dangerBtn" id="reset">Azzera tutti i dati</button></div></section>`,'home');bindNav();document.querySelector('#saveProject').onclick=()=>{state.project.name=document.querySelector('#prName').value;state.project.type=document.querySelector('#prType').value;state.project.budget=Number(document.querySelector('#prBudget').value||0);state.project.startDate=document.querySelector('#prStart').value;state.project.endDate=document.querySelector('#prEnd').value;save();home()};document.querySelector('#share').onclick=async()=>{await Share.share({title:`OperaStep · ${state.project.name}`,text:`OperaStep — ${state.project.name}\nBudget: ${eur(state.project.budget)}\nPreventivi: ${eur(totalQuotes())}\nPrevisione: ${eur(forecast())}\nPagato: ${eur(totalPaid())}\nPiano: ${taskPct()}%`})};document.querySelector('#reset').onclick=()=>{if(confirm('Cancellare tutti i dati di OperaStep da questo dispositivo?')){localStorage.removeItem(STORAGE_KEY);state=emptyState();onboarding()}}}

function route(x){({home,quotes,plan,costs,payments,project}[x]||home)()}
if(!state.onboarded||!state.project)onboarding();else home();
